<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<script type="text/javascript" src="../sh_main.js"></script>
<script type="text/javascript" src="../sh_cpp.js"></script>
<link rel="stylesheet" type="text/css" href="../styles.css">
<link rel="stylesheet" type="text/css" href="../sh_print.css">
<link rel="stylesheet" type="text/css" href="../toc.css">
<script type="text/javascript" src="../highlight.js"></script>
<title>Special functions</title>
</head>
<body>
<h2>
<dfn class="label">[except.special]</dfn><object type="application/x-oleobject" classid="clsid:1e2a7bd0-dab9-11d0-b93a-00c04fc99f9e"><param name="Keyword" value="[except.special]"></object>15.5 Special functions </h2>

<p><a class="anchor" id="p1" href="#p1">1</a>The functions <code class="sh_cpp">std::terminate()</code> (<a title="except.terminate" href="except.terminate.html">15.5.1</a>) and <code class="sh_cpp">std::unexpected()</code>
(<a title="except.unexpected" href="except.unexpected.html">15.5.2</a>) are used by the exception handling mechanism for coping with errors related to the exception
handling mechanism itself. The function <code class="sh_cpp">std::current_exception()</code> (<a title="propagation" href="propagation.html">18.8.5</a>) and the class
<code class="sh_cpp">std::nested_exception</code> (<a title="except.nested" href="except.nested.html">18.8.6</a>) can be used by a program to capture the currently handled
exception.</p>
</body>
</html>

