<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<script type="text/javascript" src="../sh_main.js"></script>
<script type="text/javascript" src="../sh_cpp.js"></script>
<!--[IF IE]>
	<script type="text/javascript" src="ierange.js"></script>
<![ENDIF]-->
<script type="text/javascript" src="../masha.min.js"></script>
<script type="text/javascript" src="../all_pack.js"></script>
<link rel="stylesheet" type="text/css" href="../css/masha.css">
<link rel="stylesheet" type="text/css" href="../sh_print.css">
<link rel="stylesheet" type="text/css" href="../toc.css">
<link rel="stylesheet" type="text/css" href="../styles.css">
<script type="text/javascript" src="../page.js"></script>

<title>uncaught_exception</title>
</head>
<body>
<h3>
<dfn class="label">[uncaught]</dfn><object type="application/x-oleobject" classid="clsid:1e2a7bd0-dab9-11d0-b93a-00c04fc99f9e"><param name="Keyword" value="[uncaught]"></object>18.8.4 <code class="sh_cpp"><dfn>uncaught_exception</dfn><object type="application/x-oleobject" classid="clsid:1e2a7bd0-dab9-11d0-b93a-00c04fc99f9e"><param name="Keyword" value="uncaught_exception"></object></code> </h3>

<pre><code class="sh_cpp">bool uncaught_exception() noexcept;</code></pre>

<p><a class="anchor" id="p1" href="#p1">1</a><em>Returns:</em> <code class="sh_cpp">true</code> after the current thread has initialized an exception object (<a title="except.throw" href="except.throw.html">15.1</a>) until
a handler for the exception (including <code class="sh_cpp">unexpected()</code> or <code class="sh_cpp">terminate()</code>) is activated
(<a title="except.handle" href="except.handle.html">15.3</a>). <span class="note">[ <em>Note:</em> This includes stack unwinding (<a title="except.ctor" href="except.ctor.html">15.2</a>). — <em>end note</em> ]</span></p>

<p><a class="anchor" id="p2" href="#p2">2</a><em>Remarks:</em> When <code class="sh_cpp">uncaught_exception()</code> returns <code class="sh_cpp">true</code>, throwing an exception can result in
a call of <code class="sh_cpp">terminate()</code> (<a title="except.terminate" href="except.terminate.html">15.5.1</a>).</p>
</body>
</html>



